server.port: 9097
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/nelsonjaimes/nttdata-bc39-grupo4-project04
          search-paths: config-server/config-data